// Generated by cbindgen from RustCore/ffi. Do not edit by hand.

#ifndef MIXER_FFI_H
#define MIXER_FFI_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct Strip Strip;

Strip *mixer_strip_create(void);

/**
 * # Safety
 * `strip` must be a pointer returned by `mixer_strip_create` and not
 * already destroyed.
 */
void mixer_strip_destroy(Strip *strip);

/**
 * # Safety
 * `strip` must be a live pointer from `mixer_strip_create`.
 */
void mixer_strip_set_gain_db(Strip *strip, float gain_db);

/**
 * # Safety
 * `strip` must be a live pointer from `mixer_strip_create`.
 */
void mixer_strip_set_muted(Strip *strip, bool muted);

/**
 * Reads back the linear gain the engine will actually apply, so the UI
 * can show the real applied value rather than re-deriving the dB→linear
 * conversion on the Swift side and risking the two drifting apart.
 * Returns 0.0 for a null pointer.
 *
 * # Safety
 * `strip` must be a live pointer from `mixer_strip_create`, or null.
 */
float mixer_strip_linear_gain(const Strip *strip);

#endif  /* MIXER_FFI_H */
